### ISSUE TITLE
inCONSISTENT* coding conventions

### ISSUE THREAD

**Issue by kyatohon** [kyatohon/SushiEngine#15]

**Comment by hau5tastic** [comment]
https://www.youtube.com/watch?v=07So_lJQyqw

**Comment by hau5tastic** [comment]
https://github.com/kyatohon/SushiEngine/wiki/Naming-Conventions

**Comment by kyatohon** [comment]
Fixed (For the most part) in 751aaadf7a6514b2bd89a3a15ff16b177574d2b5
